// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package postgres

import (
	"database/sql"
	"encoding/json"
	"time"
)

type City struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	DeletedAt sql.NullTime
}

type Hourse struct {
	ID           int64
	SectionID    int32
	Link         string
	Layout       sql.NullString
	Address      string
	Price        int32
	CurrentFloor string
	TotalFloor   string
	Shape        string
	Age          string
	Area         string
	MainArea     sql.NullString
	Commit       sql.NullString
	Raw          json.RawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type Section struct {
	ID        int64
	CityID    int32
	Name      string
	CreatedAt time.Time
	DeletedAt sql.NullTime
}
